name: 'Setup Circom'
description: 'Install and cache Circom compiler'
inputs:
  version:
    description: 'Circom version to install'
    required: false
    default: 'v2.1.8'
  sha256:
    description: 'Expected SHA-256 checksum for circom-linux-amd64'
    required: false
    default: '7a812278477b98cbe69812c382a8921289a2590e0cdfcfe321306445b4593c12'
  checksum_url:
    description: 'URL to a SHA-256 checksum file for circom-linux-amd64'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      env:
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_SHA256: ${{ inputs.sha256 }}
        INPUT_CHECKSUM_URL: ${{ inputs.checksum_url }}
      run: |
        # Validate version format (e.g., v2.1.8)
        if ! echo "$INPUT_VERSION" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
          echo "Invalid version format: $INPUT_VERSION" >&2
          exit 1
        fi

        # Validate SHA256 if provided (64 hex characters)
        if [ -n "$INPUT_SHA256" ] && ! echo "$INPUT_SHA256" | grep -qE '^[a-f0-9]{64}$'; then
          echo "Invalid SHA256 format: $INPUT_SHA256" >&2
          exit 1
        fi

        # Validate checksum URL if provided (must be HTTPS github.com)
        if [ -n "$INPUT_CHECKSUM_URL" ] && ! echo "$INPUT_CHECKSUM_URL" | grep -qE '^https://github\.com/'; then
          echo "Invalid checksum URL: must be from github.com over HTTPS" >&2
          exit 1
        fi

    - name: Cache Circom
      id: cache-circom
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      with:
        path: /usr/local/bin/circom
        key: circom-${{ runner.os }}-${{ inputs.version }}

    - name: Install Circom
      if: steps.cache-circom.outputs.cache-hit != 'true'
      shell: bash
      env:
        CIRCOM_VERSION: ${{ inputs.version }}
      run: |
        curl -L "https://github.com/iden3/circom/releases/download/${CIRCOM_VERSION}/circom-linux-amd64" -o /tmp/circom

    - name: Verify Circom checksum
      shell: bash
      env:
        CIRCOM_VERSION: ${{ inputs.version }}
        CIRCOM_SHA256: ${{ inputs.sha256 }}
        CIRCOM_CHECKSUM_URL: ${{ inputs.checksum_url }}
      run: |
        set -euo pipefail

        BIN_PATH="/usr/local/bin/circom"
        if [ -f /tmp/circom ]; then
          BIN_PATH="/tmp/circom"
        fi

        if [ ! -f "$BIN_PATH" ]; then
          echo "Circom binary not found at $BIN_PATH" >&2
          exit 1
        fi

        EXPECTED_HASH=""
        if [ -n "$CIRCOM_SHA256" ]; then
          EXPECTED_HASH="$CIRCOM_SHA256"
        else
          CHECKSUM_URLS=()
          if [ -n "$CIRCOM_CHECKSUM_URL" ]; then
            CHECKSUM_URLS+=("$CIRCOM_CHECKSUM_URL")
          else
            CHECKSUM_URLS+=("https://github.com/iden3/circom/releases/download/${CIRCOM_VERSION}/circom-linux-amd64.sha256")
            CHECKSUM_URLS+=("https://github.com/iden3/circom/releases/download/${CIRCOM_VERSION}/circom-linux-amd64.sha256sum")
          fi

          for url in "${CHECKSUM_URLS[@]}"; do
            if curl -fsL "$url" -o /tmp/circom.sha256; then
              EXPECTED_HASH="$(awk '{print $1}' /tmp/circom.sha256 | tr -d '\r\n')"
              break
            fi
          done
        fi

        if [ -z "$EXPECTED_HASH" ]; then
          echo "Unable to resolve Circom checksum." >&2
          echo "Provide inputs.sha256 or inputs.checksum_url for verification." >&2
          exit 1
        fi

        echo "${EXPECTED_HASH}  $BIN_PATH" | sha256sum -c -

        if [ "$BIN_PATH" = "/tmp/circom" ]; then
          chmod +x /tmp/circom
          sudo mv /tmp/circom /usr/local/bin/circom
        fi

    - name: Verify Circom installation
      shell: bash
      run: circom --version
